from enum import Enum

OPERATION_CODE_WORKING = '0'
OPERATION_CODE_NOT_WORKING = '1'

class Orientation(Enum):
    TOP = '3'
    BOTTOM = '4'
    LEFT = '5'
    RIGHT = '6'

CLIENT_APPROVED = '7'
CLIENT_DENINED_PASSCODE_WRONG = '8'
CLIENT_DENINED_ORIENTATION_UNAVAILABLE = '9'
CLIENT_DEATTACHED = '10'